<?php
declare(strict_types=1);

/**
 * Registry of single-blob (or single-member archive) formats for literal_pac.
 * Mirrors intent of ../file_types/types.php “compressed” category; extend both together when that file exists in-tree.
 *
 * @var list<array{
 *   id: string,
 *   label: string,
 *   extensions: list<string>,
 *   handler: string,
 *   magic_prefix: ?string,
 *   tools: list<string>,
 *   notes?: string
 * }>
 */
const FRACTAL_ZIP_LITERALPAC_REGISTRY = [
	[
		'id' => 'gzip',
		'label' => 'gzip (DEFLATE)',
		'extensions' => ['gz', 'svgz', 'vgz'],
		'handler' => 'gzip_variants',
		'magic_prefix' => "\x1F\x8B",
		'tools' => ['gzip', 'pigz', 'zopfli'],
		'notes' => 'VGM .vgz rips are gzip members (decompress to .vgm). FRACTAL_ZIP_LITERALPAC_GZIP_ENGINE=auto|gzip|pigz|zopfli; ZOPFLI tries only if tool exists and FRACTAL_ZIP_LITERALPAC_ZOPFLI=1 (slow).',
	],
	[
		'id' => 'bzip2',
		'label' => 'bzip2',
		'extensions' => ['bz2'],
		'handler' => 'bzip2',
		'magic_prefix' => 'BZ',
		'tools' => ['bzip2', 'pbzip2'],
		'notes' => 'Optional FRACTAL_ZIP_LITERALPAC_PBZIP2_P (non-off) uses pbzip2 -p… on PATH vs stock bzip2.',
	],
	[
		'id' => 'xz',
		'label' => 'xz (LZMA2)',
		'extensions' => ['xz'],
		'handler' => 'xz',
		'magic_prefix' => "\xFD\x37\x7A\x58\x5A\x00",
		'tools' => ['xz'],
	],
	[
		'id' => 'zstd',
		'label' => 'Zstandard',
		'extensions' => ['zst'],
		'handler' => 'zstd',
		'magic_prefix' => "\x28\xB5\x2F\xFD",
		'tools' => ['zstd'],
	],
	[
		'id' => 'lz4',
		'label' => 'LZ4 frame',
		'extensions' => ['lz4'],
		'handler' => 'lz4',
		'magic_prefix' => "\x04\x22\x4D\x18",
		'tools' => ['lz4'],
	],
	[
		'id' => 'brotli',
		'label' => 'Brotli',
		'extensions' => ['br'],
		'handler' => 'brotli',
		'magic_prefix' => null,
		'tools' => ['brotli'],
	],
	[
		'id' => 'lzip',
		'label' => 'lzip',
		'extensions' => ['lzip'],
		'handler' => 'lzip',
		'magic_prefix' => 'LZIP',
		'tools' => ['lzip', 'plzip'],
		'notes' => 'Optional FRACTAL_ZIP_LITERALPAC_PLZIP_THREADS (non-off) uses plzip -n… on PATH vs lzip; can change size vs lzip slightly.',
	],
	[
		'id' => 'lzma_raw',
		'label' => 'raw LZMA (.lz not lzip)',
		'extensions' => ['lz'],
		'handler' => 'lzma_sniff',
		'magic_prefix' => null,
		'tools' => ['lzma', 'lzip'],
		'notes' => 'If magic is LZIP, use lzip; else lzma(1) stream. With fractal_zip: same -T tokens as xz (FRACTAL_ZIP_XZ_*).',
	],
	[
		'id' => 'woff2',
		'label' => 'WOFF2 font',
		'extensions' => ['woff2'],
		'handler' => 'woff2',
		'magic_prefix' => 'wOF2',
		'tools' => ['woff2_decompress', 'woff2_compress'],
	],
	[
		'id' => 'zip_single',
		'label' => 'ZIP (one member, re-packed with max deflate if smaller)',
		'extensions' => ['zip'],
		'handler' => 'zip_single',
		'magic_prefix' => "PK\x03\x04",
		'tools' => ['php-zip'],
		'notes' => 'Any compression method libzip can decompress via getFromIndex; output always deflate L9 when setCompressionIndex exists.',
	],
	[
		'id' => '7z_single',
		'label' => '7z (exactly one file member)',
		'extensions' => ['7z'],
		'handler' => 'seven_single',
		'magic_prefix' => "7z\xBC\xAF\x27\x1C",
		'tools' => ['7z', '7za', '7zz'],
	],
	[
		'id' => 'pdf_native_flate',
		'label' => 'PDF /FlateDecode (zlib-9 or raw DEFLATE-9, PHP only)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_native_flate',
		'magic_prefix' => '%PDF',
		'tools' => [],
		'notes' => 'First PDF step. /FlateDecode re-zlib-9 or raw-9 if smaller; no zopfli in-PDF. FRACTAL_ZIP_LITERALPAC_PDF_NATIVE=0 disables. Skips DCT/JPX/JBIG2/CCITT.',
	],
	[
		'id' => 'pdf_dct_jpeg',
		'label' => 'PDF /DCTDecode (jpegtran, lossless multi-candidate, multi-pass)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_dct_jpeg',
		'magic_prefix' => '%PDF',
		'tools' => ['jpegtran'],
		'notes' => 'After Flate. FRACTAL_ZIP_LITERALPAC_PDF_JPEG=0 disables. Multi-pass: FRACTAL_ZIP_PDF_JPEG_JPEGTRAN_MAX_PASSES. Lossy: FRACTAL_ZIP_PDF_JPEG_SEMANTIC=1; min Mpix + BPP gate (LOSSY_* env); adaptive min-savings; PPM diff MAX_PPM_CHANNEL_DIFF. Indirect /Length n 0 R not rewritten here.',
	],
	[
		'id' => 'pdf_jbig2',
		'label' => 'PDF /JBIG2Decode (jbig2dec -e + jbig2/jbig2enc, lossless PBM verify)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_jbig2',
		'magic_prefix' => '%PDF',
		'tools' => ['jbig2dec', 'jbig2'],
		'notes' => 'After JPEG step. Requires jbig2dec; encoder jbig2 or jbig2enc on PATH or no-op. FRACTAL_ZIP_LITERALPAC_PDF_JBIG2=0 disables. Globals stream (two-arg jbig2dec) not handled in v1.',
	],
	[
		'id' => 'pdf_jpx',
		'label' => 'PDF /JPXDecode (OpenJPEG opj_decompress/opj_compress, lossless decode compare)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_jpx',
		'magic_prefix' => '%PDF',
		'tools' => ['opj_decompress', 'opj_compress'],
		'notes' => 'After JBIG2. FRACTAL_ZIP_LITERALPAC_PDF_JPX=0 disables.',
	],
	[
		'id' => 'pdf_ccitt',
		'label' => 'PDF /CCITTFaxDecode (fax2tiff -4 + tiffcp -c g4 + strip extract; G4-only v1)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_ccitt',
		'magic_prefix' => '%PDF',
		'tools' => ['fax2tiff', 'tiffcp', 'convert'],
		'notes' => 'After JPX. v1: only streams that decode with fax2tiff -4 (Group 4). FRACTAL_ZIP_LITERALPAC_PDF_CCITT=0 disables.',
	],
	[
		'id' => 'pdf_qpdf',
		'label' => 'PDF qpdf rewrite (object streams, lossless, opt-in)',
		'extensions' => ['pdf'],
		'handler' => 'pdf_qpdf',
		'magic_prefix' => '%PDF',
		'tools' => ['qpdf', 'pdfinfo'],
		'notes' => 'Default off (FRACTAL_ZIP_LITERALPAC_PDF_QPDF=1 to enable). Structural PDF rewrite; use if you want qpdf after in-stream re-packs. --object-streams=generate with check and pdfinfo page count.',
	],
	[
		'id' => 'mpq_mopaq',
		'label' => 'MoPAQ / MPQ (Blizzard container; StarCraft II .SC2Replay, Warcraft III .w3x, etc.)',
		'extensions' => ['sc2replay', 'mpq', 'w3x'],
		'handler' => 'mpq_optional',
		'magic_prefix' => 'MPQ',
		'tools' => ['python3', 'smpq'],
		'notes' => 'Magic "MPQ" + version byte (e.g. 0x1A classic, 0x1B SC2). Stream: repack-smaller (smpq, semantic) then optional FRACTAL_ZIP_LITERALPAC_MPQ_TOOL. Semantic peel (mode 11): same script + mpyq; default always peels when unpack succeeds. FRACTAL_ZIP_LITERAL_SEMANTIC_MPQ_PROXY_GATE=1 restores gzip-1 proxy gate. FRACTAL_ZIP_LITERALPAC_MPQ_REPACK=0 disables repack-smaller.',
	],
];
