#!/usr/bin/env bash
# Write examples/fz_fractal_local_env.php with FRACTAL_ZIP_* paths for web + CLI extract parity.
# Run on the machine that serves fzc_compress.php / fzc_extract.php (e.g. freement.cloud via SSH).
#
# Usage:
#   ./examples/setup_fractal_zip_extract_tools_env.sh
#   ./examples/setup_fractal_zip_extract_tools_env.sh /home/freement/public_html/fractal_zip/examples/fz_fractal_local_env.php
#
# Install missing tools first (Arch/Manjaro example):
#   sudo pacman -S --needed p7zip zstd brotli xz
#   # FreeArc `arc` is not always packaged — build or copy a static binary to /home/freement/bin/arc
#
# Then verify:
#   bash scripts/fzc_live_setup_check.sh
#   php examples/fzc_capability_report.php --as-web --human

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="${1:-"$SCRIPT_DIR/fz_fractal_local_env.php"}"

if [[ "$OUT" != /* ]]; then
	OUT="$SCRIPT_DIR/$OUT"
fi

pick_exe() {
	local p
	for p in "$@"; do
		if [[ -n "$p" && -f "$p" && -x "$p" ]]; then
			realpath "$p"
			return 0
		fi
	done
	return 1
}

HOME_DIR="${HOME:-/home/freement}"
HOME_DIR="${HOME_DIR%/}"
FREEMENT_BIN="/home/freement/bin"

declare -A FOUND=()
declare -A MISSING=()

record() {
	local env="$1"
	local path="$2"
	if [[ -n "$path" ]]; then
		FOUND["$env"]="$path"
	else
		MISSING["$env"]=1
	fi
}

record FRACTAL_ZIP_ZPAQ "$(pick_exe \
	"$FREEMENT_BIN/zpaq" "$HOME_DIR/bin/zpaq" /usr/bin/zpaq /usr/local/bin/zpaq \
	2>/dev/null || true)"

record FRACTAL_ZIP_7Z "$(pick_exe \
	"$FREEMENT_BIN/7zz" "$FREEMENT_BIN/7z" "$FREEMENT_BIN/7za" \
	"$HOME_DIR/bin/7zz" "$HOME_DIR/bin/7z" \
	/usr/bin/7zz /usr/bin/7z /usr/bin/7za /usr/local/bin/7zz /usr/local/bin/7z \
	2>/dev/null || true)"

record FRACTAL_ZIP_ARC "$(pick_exe \
	"$FREEMENT_BIN/arc" "$HOME_DIR/.local/bin/arc" "$HOME_DIR/bin/arc" \
	/usr/bin/arc /usr/local/bin/arc \
	2>/dev/null || true)"

record FRACTAL_ZIP_BROTLI "$(pick_exe \
	"$FREEMENT_BIN/brotli" /usr/bin/brotli /usr/local/bin/brotli \
	2>/dev/null || true)"

record FRACTAL_ZIP_XZ "$(pick_exe \
	"$FREEMENT_BIN/xz" /usr/bin/xz /usr/local/bin/xz \
	2>/dev/null || true)"

record FRACTAL_ZIP_ZSTD "$(pick_exe \
	"$FREEMENT_BIN/zstd" "$HOME_DIR/bin/zstd" /usr/bin/zstd /usr/local/bin/zstd \
	2>/dev/null || true)"

{
	echo '<?php'
	echo 'declare(strict_types=1);'
	echo ''
	echo '/**'
	echo ' * Local extract tool paths — generated by examples/setup_fractal_zip_extract_tools_env.sh'
	echo ' * Do not commit (gitignored). Loaded by fz_local_env_bootstrap.php.'
	echo ' */'
	echo ''
	echo "putenv('FZC_WEB_ENFORCE_EXTRACT_COMPAT=1');"
	echo "putenv('FZC_WEB_MAX_UPLOAD_BYTES=33554432');"
	echo "putenv('FZC_WEB_MAX_EXTRACT_ARCHIVE_BYTES=335544320');"
	echo ''

	for env in FRACTAL_ZIP_ZPAQ FRACTAL_ZIP_7Z FRACTAL_ZIP_ARC FRACTAL_ZIP_BROTLI FRACTAL_ZIP_XZ FRACTAL_ZIP_ZSTD; do
		path="${FOUND[$env]:-}"
		if [[ -n "$path" ]]; then
			printf "putenv('%s=' . %s);\n" "$env" "$(php -r 'echo var_export($argv[1], true);' "$path")"
		fi
	done
} >"$OUT"

echo "Wrote $OUT"
for env in FRACTAL_ZIP_ZPAQ FRACTAL_ZIP_7Z FRACTAL_ZIP_ARC FRACTAL_ZIP_BROTLI FRACTAL_ZIP_XZ FRACTAL_ZIP_ZSTD; do
	path="${FOUND[$env]:-}"
	if [[ -n "$path" ]]; then
		echo "  $env=$path"
	else
		echo "  MISSING $env" >&2
	fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
	echo "" >&2
	echo "Install missing tools, then re-run this script. See docs/WEB_LOCAL_PARITY.md" >&2
	exit 1
fi

echo ""
echo "Restart PHP-FPM/LiteSpeed so workers pick up the new env file."
echo "Verify: cd $REPO && bash scripts/fzc_live_setup_check.sh"
