#!/usr/bin/env bash
# Write examples/fz_fractal_local_env.php so PHP (web + CLI) sees FRACTAL_ZIP_ZPAQ.
# fz_local_env_bootstrap.php loads that file before fractal_zip.php.
#
# Default binary: /home/freement/bin/zpaq
# Override:  ZPAQ_BIN=/other/zpaq ./setup_fractal_zip_zpaq_env.sh
# Optional: output path (default: fz_fractal_local_env.php next to this script).
#   ./setup_fractal_zip_zpaq_env.sh /var/www/site/examples/fz_fractal_local_env.php

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZPAQ_BIN="${ZPAQ_BIN:-/home/freement/bin/zpaq}"
OUT="${1:-"$SCRIPT_DIR/fz_fractal_local_env.php"}"

if [[ "$OUT" != /* ]]; then
	OUT="$SCRIPT_DIR/$OUT"
fi

if [[ ! -f "$ZPAQ_BIN" ]]; then
	echo "error: file not found: $ZPAQ_BIN" >&2
	echo "  Set ZPAQ_BIN to the full path of your zpaq executable." >&2
	exit 1
fi
if [[ ! -x "$ZPAQ_BIN" ]]; then
	echo "error: not executable: $ZPAQ_BIN (try: chmod +x)" >&2
	exit 1
fi

export ZPAQ_BIN
export OUT
php <<'PHP'
<?php
declare(strict_types=1);

$bin = getenv('ZPAQ_BIN');
$out = getenv('OUT');
if (!is_string($bin) || $bin === '' || !is_string($out) || $out === '') {
	fwrite(STDERR, "internal error: missing ZPAQ_BIN or OUT\n");
	exit(1);
}
if (!is_executable($bin)) {
	fwrite(STDERR, "not executable: {$bin}\n");
	exit(1);
}
$rp = realpath($bin);
if ($rp === false) {
	fwrite(STDERR, "realpath failed: {$bin}\n");
	exit(1);
}
$body = "<?php\n"
	. "declare(strict_types=1);\n\n"
	. "/**\n"
	. " * Local tool paths — generated by examples/setup_fractal_zip_zpaq_env.sh\n"
	. " * Do not commit (listed in examples/.gitignore).\n"
	. " * Loaded by fz_local_env_bootstrap.php before fractal_zip.php.\n"
	. " */\n\n"
	. "putenv('FRACTAL_ZIP_ZPAQ=' . " . var_export($rp, true) . ");\n";

if (file_put_contents($out, $body) === false) {
	fwrite(STDERR, "cannot write: {$out}\n");
	exit(1);
}
echo "Wrote {$out}\n";
echo "FRACTAL_ZIP_ZPAQ={$rp}\n";
PHP

echo ""
echo "Restart PHP-FPM or Apache if the site still cannot find zpaq (long-lived workers)."
