<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                      "@w{QPKF54RE}">
<html xmlns="@w{SZTDMW9J}" xml:lang="en" lang="en">
<head>
 <title>PHP: Show Source</title>
 <style type="text/css" media="all">
  @import url("@w{2XX58MCD}");
  @import url("@w{884KPP5P}");
  
 </style>
 <!--[if IE]><![if gte IE 6]><![endif]-->
  <style type="text/css" media="print">
   @import url("@w{M98RFPWS}");
  </style>
 <!--[if IE]><![endif]><![endif]-->
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
 <link rel="shortcut icon" href="@w{NGWYKJ8F}" />
 <link rel="canonical" href="http://php.net/source.php" />
 <script type="text/javascript" src="@w{4SAB2YT3}"></script>
 <base href="http://www.php.net/source.php" />
</head>
<body>

<div id="headnav">
 <a href="/" rel="home"><img src="@w{BJ2SG82M}"
 alt="PHP" width="120" height="67" id="phplogo" /></a>
 <div id="headmenu">
  <a href="/downloads.php">downloads</a> |
  <a href="/docs.php">documentation</a> |
  <a href="/FAQ.php">faq</a> |
  <a href="/support.php">getting help</a> |
  <a href="/mailing-lists.php">mailing lists</a> |
  <a href="/license">licenses</a> |
  <a href="@w{WEGCK3BV}">wiki</a> |
  <a href="@w{JBVFFY7T}">reporting bugs</a> |
  <a href="/sites.php">php.net sites</a> |
  <a href="/conferences/">conferences</a> |
  <a href="/my.php">my php.net</a>
 </div>
</div>

<div id="headsearch">
 <form method="post" action="/search.php" id="topsearch">
  <p>
   <span title="Keyboard shortcut: Alt+S (Win), Ctrl+S (Apple)">
    <span class="shortkey">s</span>earch for
   </span>
   <input type="text" name="pattern" value="" size="30" accesskey="s" />
   <span>in the</span>
   <select name="show">
    <option value="all"      >all php.net sites</option>
    <option value="local"    >this mirror only</option>
    <option value="quickref" selected="selected">function list</option>
    <option value="manual"   >online documentation</option>
    <option value="bugdb"    >bug database</option>
    <option value="news_archive">Site News Archive</option>
    <option value="changelogs">All Changelogs</option>
    <option value="pear"     >just pear.php.net</option>
    <option value="pecl"     >just pecl.php.net</option>
    <option value="talks"    >just talks.php.net</option>
    <option value="maillist" >general mailing list</option>
    <option value="devlist"  >developer mailing list</option>
    <option value="phpdoc"   >documentation mailing list</option>
   </select>
   <input type="image"
          src="@w{XXWWP636}"
          class="submit" alt="search" />
  </p>
 </form>
</div>

<div id="layout_2">
 <div id="leftbar">

<h3>Our source is open</h3>
<p>
 The syntax highlighted source is automatically generated by PHP from
 the plaintext script.
 If you're interested in what's behind the several functions we
 used, you can always take a look at the source of the following files:
</p>

<ul class="toc">
 <li><a href="/source.php?url=/include/prepend.inc">prepend.inc</a></li>
 <li><a href="/source.php?url=/include/site.inc">site.inc</a></li>
 <li><a href="/source.php?url=/include/mirrors.inc">mirrors.inc</a></li>
 <li><a href="/source.php?url=/include/countries.inc">countries.inc</a></li>
 <li><a href="/source.php?url=/include/languages.inc">languages.inc</a></li>
 <li><a href="/source.php?url=/include/langchooser.inc">langchooser.inc</a></li>
 <li><a href="/source.php?url=/include/ip-to-country.inc">ip-to-country.inc</a></li>
 <li><a href="/source.php?url=/include/layout.inc">layout.inc</a></li>
 <li><a href="/source.php?url=/include/last_updated.inc">last_updated.inc</a></li>
 <li><a href="/source.php?url=/include/shared-manual.inc">shared-manual.inc</a></li>
 <li><a href="/source.php?url=/include/manual-lookup.inc">manual-lookup.inc</a></li>
</ul>

<p>
 Of course, if you want to see the <a href="/source.php?url=/source.php">source
 of this page</a>, we have it available.
 You can also browse the Git repository for this website on
 <a href="http://git.php.net/?p=web/php.git;a=summary">git.php.net</a>.
</p>

 </div>
 <div id="content" class=".">
<h1>Source of: /manual/en/langref.php</h1><div class="phpcode"><code><span class="html">
<span class="default">&lt;?php<br />
</span><span class="keyword">include_once </span><span class="default">$_SERVER</span><span class="keyword">[</span><span class="string">'DOCUMENT_ROOT'</span><span class="keyword">] . </span><span class="string">'/include/shared-manual.inc'</span><span class="keyword">;<br />
</span><span class="default">$TOC </span><span class="keyword">= array();<br />
</span><span class="default">$PARENTS </span><span class="keyword">= array();<br />
include_once </span><span class="default">dirname</span><span class="keyword">(</span><span class="default">__FILE__</span><span class="keyword">) .</span><span class="string">"/toc/index.inc"</span><span class="keyword">;<br />
</span><span class="default">$setup </span><span class="keyword">= array (<br />
&nbsp; </span><span class="string">'home' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'index.php'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'PHP Manual'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'head' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'UTF-8'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'en'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'this' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'langref.php'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'Language Reference'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'up' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'index.php'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'PHP Manual'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'prev' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'configuration.changes.php'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'How to change configuration settings'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'next' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">0 </span><span class="keyword">=&gt; </span><span class="string">'language.basic-syntax.php'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">=&gt; </span><span class="string">'Basic syntax'</span><span class="keyword">,<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'alternatives' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp; ),<br />
&nbsp; </span><span class="string">'extra_header_links' </span><span class="keyword">=&gt; <br />
&nbsp; array (<br />
&nbsp;&nbsp;&nbsp; </span><span class="string">'rel' </span><span class="keyword">=&gt; </span><span class="string">'alternate'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="string">'href' </span><span class="keyword">=&gt; </span><span class="string">'/manual/en/feeds/langref.atom'</span><span class="keyword">,<br />
&nbsp;&nbsp;&nbsp; </span><span class="string">'type' </span><span class="keyword">=&gt; </span><span class="string">'application/atom+xml'</span><span class="keyword">,<br />
&nbsp; ),<br />
);<br />
</span><span class="default">$setup</span><span class="keyword">[</span><span class="string">"toc"</span><span class="keyword">] = </span><span class="default">$TOC</span><span class="keyword">;<br />
</span><span class="default">$setup</span><span class="keyword">[</span><span class="string">"parents"</span><span class="keyword">] = </span><span class="default">$PARENTS</span><span class="keyword">;<br />
</span><span class="default">manual_setup</span><span class="keyword">(</span><span class="default">$setup</span><span class="keyword">);<br />
<br />
</span><span class="default">manual_header</span><span class="keyword">();<br />
</span><span class="default">?&gt;<br />
</span>&lt;div id="langref" class="book"&gt;<br />
&nbsp; &lt;h1 class="title"&gt;Language Reference&lt;/h1&gt;<br />
&nbsp; <br />
<br />
&nbsp;<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
&nbsp;<br />
&nbsp;<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
&nbsp;<br />
<br />
&nbsp;<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
&nbsp;<br />
<br />
<br />
<br />
&nbsp; <br />
<br />
<br />
<br />
<br />
<br />
<br />
&nbsp;&lt;ul class="chunklist chunklist_book"&gt;&lt;li&gt;&lt;a href="language.basic-syntax.php"&gt;Basic syntax&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.basic-syntax.phptags.php"&gt;PHP tags&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.basic-syntax.phpmode.php"&gt;Escaping from HTML&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.basic-syntax.instruction-separation.php"&gt;Instruction separation&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.basic-syntax.comments.php"&gt;Comments&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.php"&gt;Types&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.types.intro.php"&gt;Introduction&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.boolean.php"&gt;Booleans&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.integer.php"&gt;Integers&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.float.php"&gt;Floating point numbers&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.string.php"&gt;Strings&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.array.php"&gt;Arrays&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.object.php"&gt;Objects&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.resource.php"&gt;Resources&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.null.php"&gt;NULL&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.callable.php"&gt;Callbacks&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.pseudo-types.php"&gt;Pseudo-types and variables used in this documentation&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.types.type-juggling.php"&gt;Type Juggling&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.variables.php"&gt;Variables&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.variables.basics.php"&gt;Basics&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.variables.predefined.php"&gt;Predefined Variables&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.variables.scope.php"&gt;Variable scope&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.variables.variable.php"&gt;Variable variables&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.variables.external.php"&gt;Variables From External Sources&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.constants.php"&gt;Constants&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.constants.syntax.php"&gt;Syntax&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.constants.predefined.php"&gt;Magic constants&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.expressions.php"&gt;Expressions&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.php"&gt;Operators&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.operators.precedence.php"&gt;Operator Precedence&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.arithmetic.php"&gt;Arithmetic Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.assignment.php"&gt;Assignment Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.bitwise.php"&gt;Bitwise Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.comparison.php"&gt;Comparison Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.errorcontrol.php"&gt;Error Control Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.execution.php"&gt;Execution Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.increment.php"&gt;Incrementing/Decrementing Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.logical.php"&gt;Logical Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.string.php"&gt;String Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.array.php"&gt;Array Operators&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.operators.type.php"&gt;Type Operators&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.control-structures.php"&gt;Control Structures&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="control-structures.intro.php"&gt;Introduction&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.if.php"&gt;if&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.else.php"&gt;else&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.elseif.php"&gt;elseif/else if&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.alternative-syntax.php"&gt;Alternative syntax for control structures&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.while.php"&gt;while&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.do.while.php"&gt;do-while&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.for.php"&gt;for&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.foreach.php"&gt;foreach&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.break.php"&gt;break&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.continue.php"&gt;continue&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.switch.php"&gt;switch&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.declare.php"&gt;declare&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="function.return.php"&gt;return&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="function.require.php"&gt;require&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="function.include.php"&gt;include&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="function.require-once.php"&gt;require_once&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="function.include-once.php"&gt;include_once&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="control-structures.goto.php"&gt;goto&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.functions.php"&gt;Functions&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="functions.user-defined.php"&gt;User-defined functions&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="functions.arguments.php"&gt;Function arguments&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="functions.returning-values.php"&gt;Returning values&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="functions.variable-functions.php"&gt;Variable functions&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="functions.internal.php"&gt;Internal (built-in) functions&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="functions.anonymous.php"&gt;Anonymous functions&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.php"&gt;Classes and Objects&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="oop5.intro.php"&gt;Introduction&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.basic.php"&gt;The Basics&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.properties.php"&gt;Properties&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.constants.php"&gt;Class Constants&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.autoload.php"&gt;Autoloading Classes&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.decon.php"&gt;Constructors and Destructors&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.visibility.php"&gt;Visibility&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.inheritance.php"&gt;Object Inheritance&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.paamayim-nekudotayim.php"&gt;Scope Resolution Operator (::)&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.static.php"&gt;Static Keyword&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.abstract.php"&gt;Class Abstraction&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.interfaces.php"&gt;Object Interfaces&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.traits.php"&gt;Traits&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.overloading.php"&gt;Overloading&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.iterations.php"&gt;Object Iteration&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.magic.php"&gt;Magic Methods&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.final.php"&gt;Final Keyword&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.cloning.php"&gt;Object Cloning&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.object-comparison.php"&gt;Comparing Objects&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.typehinting.php"&gt;Type Hinting&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.late-static-bindings.php"&gt;Late Static Bindings&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.references.php"&gt;Objects and references&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.serialization.php"&gt;Object Serialization&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.oop5.changelog.php"&gt;OOP Changelog&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.php"&gt;Namespaces&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.namespaces.rationale.php"&gt;Namespaces overview&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.definition.php"&gt;Defining namespaces&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.nested.php"&gt;Declaring sub-namespaces&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.definitionmultiple.php"&gt;Defining multiple namespaces in the same file&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.basics.php"&gt;Using namespaces: Basics&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.dynamic.php"&gt;Namespaces and dynamic language features&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.nsconstants.php"&gt;namespace keyword and __NAMESPACE__ constant&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.importing.php"&gt;Using namespaces: Aliasing/Importing&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.global.php"&gt;Global space&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.fallback.php"&gt;Using namespaces: fallback to global function/constant&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.rules.php"&gt;Name resolution rules&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.namespaces.faq.php"&gt;FAQ: things you need to know about namespaces&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.exceptions.php"&gt;Exceptions&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.exceptions.extending.php"&gt;Extending Exceptions&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.php"&gt;References Explained&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.references.whatare.php"&gt;What References Are&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.whatdo.php"&gt;What References Do&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.arent.php"&gt;What References Are Not&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.pass.php"&gt;Passing by Reference&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.return.php"&gt;Returning References&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.unset.php"&gt;Unsetting References&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="language.references.spot.php"&gt;Spotting References&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.php"&gt;Predefined Variables&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="language.variables.superglobals.php"&gt;Superglobals&lt;/a&gt; — Superglobals are built-in variables that are always available in all scopes&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.globals.php"&gt;$GLOBALS&lt;/a&gt; — References all variables available in global scope&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.server.php"&gt;$_SERVER&lt;/a&gt; — Server and execution environment information&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.get.php"&gt;$_GET&lt;/a&gt; — HTTP GET variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.post.php"&gt;$_POST&lt;/a&gt; — HTTP POST variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.files.php"&gt;$_FILES&lt;/a&gt; — HTTP File Upload variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.request.php"&gt;$_REQUEST&lt;/a&gt; — HTTP Request variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.session.php"&gt;$_SESSION&lt;/a&gt; — Session variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.environment.php"&gt;$_ENV&lt;/a&gt; — Environment variables&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.cookies.php"&gt;$_COOKIE&lt;/a&gt; — HTTP Cookies&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.phperrormsg.php"&gt;$php_errormsg&lt;/a&gt; — The previous error message&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.httprawpostdata.php"&gt;$HTTP_RAW_POST_DATA&lt;/a&gt; — Raw POST data&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.httpresponseheader.php"&gt;$http_response_header&lt;/a&gt; — HTTP response headers&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.argc.php"&gt;$argc&lt;/a&gt; — The number of arguments passed to script&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.variables.argv.php"&gt;$argv&lt;/a&gt; — Array of arguments passed to script&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.exceptions.php"&gt;Predefined Exceptions&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="class.exception.php"&gt;Exception&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="class.errorexception.php"&gt;ErrorException&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="reserved.interfaces.php"&gt;Predefined Interfaces&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="class.traversable.php"&gt;Traversable&lt;/a&gt; — The Traversable interface&lt;/li&gt;&lt;li&gt;&lt;a href="class.iterator.php"&gt;Iterator&lt;/a&gt; — The Iterator interface&lt;/li&gt;&lt;li&gt;&lt;a href="class.iteratoraggregate.php"&gt;IteratorAggregate&lt;/a&gt; — The IteratorAggregate interface&lt;/li&gt;&lt;li&gt;&lt;a href="class.arrayaccess.php"&gt;ArrayAccess&lt;/a&gt; — The ArrayAccess interface&lt;/li&gt;&lt;li&gt;&lt;a href="class.serializable.php"&gt;Serializable&lt;/a&gt; — The Serializable interface&lt;/li&gt;&lt;li&gt;&lt;a href="class.closure.php"&gt;Closure&lt;/a&gt; — The Closure class&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="context.php"&gt;Context options and parameters&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="context.socket.php"&gt;Socket context options&lt;/a&gt; — Socket context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.http.php"&gt;HTTP context options&lt;/a&gt; — HTTP context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.ftp.php"&gt;FTP context options&lt;/a&gt; — FTP context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.ssl.php"&gt;SSL context options&lt;/a&gt; — SSL context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.curl.php"&gt;CURL context options&lt;/a&gt; — CURL context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.phar.php"&gt;Phar context options&lt;/a&gt; — Phar context option listing&lt;/li&gt;&lt;li&gt;&lt;a href="context.params.php"&gt;Context parameters&lt;/a&gt; — Context parameter listing&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.php"&gt;Supported Protocols and Wrappers&lt;/a&gt;&lt;ul class="chunklist chunklist_book chunklist_children"&gt;&lt;li&gt;&lt;a href="wrappers.file.php"&gt;file://&lt;/a&gt; — Accessing local filesystem&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.http.php"&gt;http://&lt;/a&gt; — Accessing HTTP(s) URLs&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.ftp.php"&gt;ftp://&lt;/a&gt; — Accessing FTP(s) URLs&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.php.php"&gt;php://&lt;/a&gt; — Accessing various I/O streams&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.compression.php"&gt;zlib://&lt;/a&gt; — Compression Streams&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.data.php"&gt;data://&lt;/a&gt; — Data (RFC 2397)&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.glob.php"&gt;glob://&lt;/a&gt; — Find pathnames matching pattern&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.phar.php"&gt;phar://&lt;/a&gt; — PHP Archive&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.ssh2.php"&gt;ssh2://&lt;/a&gt; — Secure Shell 2&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.rar.php"&gt;rar://&lt;/a&gt; — RAR&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.audio.php"&gt;ogg://&lt;/a&gt; — Audio streams&lt;/li&gt;&lt;li&gt;&lt;a href="wrappers.expect.php"&gt;expect://&lt;/a&gt; — Process Interaction Streams&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;<span class="default">&lt;?php manual_footer</span><span class="keyword">(); </span><span class="default">?&gt;</span>
</span>
</code></div>
 </div>
 <div class="cleaner">&nbsp;</div>
</div>

<div id="footnav">
   <a href="/source.php?url=/source.php">show source</a> |
 <a href="/credits.php">credits</a> |
 <a href="/stats/">stats</a> |
 <a href="/sitemap.php">sitemap</a> |
 <a href="/contact.php">contact</a> |
 <a href="/contact.php#ads">advertising</a> |
 <a href="/mirrors.php">mirror sites</a>
</div>

<div id="pagefooter">
 <div id="copyright">
  <a href="/copyright.php">Copyright &copy; 2001-2012 The PHP Group</a><br />
  All rights reserved.
 </div>

 <div id="thismirror">
  <a href="/mirror.php">This mirror</a> generously provided by:
  <a href="@w{TDAY9QJ9}">Yahoo! Inc.</a><br />
  Last updated: Tue Jul 31 20:41:05 2012 UTC
 </div>
</div>
<!--[if IE 6]>
<script type="text/javascript">
    /*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"@w{8JFFCNVW}"></"+"script>"); var __noconflict = true; }
    var IE6UPDATE_OPTIONS = {
        icons_path: "/ie6update/images/"
    }
</script>
<script type="text/javascript" src="/ie6update/ie6update.js"></script>
<![endif]-->
</body>
</html>